version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo pre build
  build:
    commands:
      - cdk deploy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - node_modules